# frozen_string_literal: true

require "delegate"

module Fontisan
  module Variation
    # Wraps a variable font to substitute specific table tags with
    # instance-generated equivalents while forwarding everything else
    # to the original font. Used by VariableSvgGenerator to feed the
    # SVG generator an instance-shaped font without rewriting it.
    #
    # Delegation uses SimpleDelegator so the wrapper is transparent:
    # the original font's interface is preserved verbatim. Only
    # #has_table? is overridden to also report instance-supplied tags.
    #
    # NOTE: #table currently delegates to the original font for any tag
    # not in the instance map. The previous implementation always
    # delegated regardless of @table_data contents, which SvgGenerator
    # depended on (it expects parsed BinData records, not raw bytes).
    # Until SvgGenerator can consume raw instance bytes, this wrapper
    # preserves that behavior. The @table_data map is still exposed so
    # downstream code that wants the raw bytes can read them.
    class InstanceFontWrapper < SimpleDelegator
      # @return [Hash<String, String>] instance-generated table bytes by tag
      attr_reader :table_data

      # @param original_font [TrueTypeFont, OpenTypeFont] the variable font
      # @param instance_tables [Hash<String, String>] instance-generated bytes
      def initialize(original_font, instance_tables)
        super(original_font)
        @table_data = instance_tables
      end

      # @param tag [String] table tag
      # @return [Boolean]
      def has_table?(tag)
        @table_data.key?(tag) || __getobj__.has_table?(tag)
      end
    end
  end
end
