# frozen_string_literal: true

# Autoload hub for the Fontisan::Tables namespace.

module Fontisan
  module Tables
    autoload :Cbdt, "fontisan/tables/cbdt"
    autoload :Cblc, "fontisan/tables/cblc"
    autoload :Cff, "fontisan/tables/cff"
    autoload :Cff2, "fontisan/tables/cff2"
    autoload :Cmap, "fontisan/tables/cmap"
    autoload :CmapTable, "fontisan/tables/cmap_table"
    autoload :Colr, "fontisan/tables/colr"
    autoload :CompoundGlyph, "fontisan/tables/glyf/compound_glyph"
    autoload :CompoundGlyphResolver, "fontisan/tables/glyf/compound_glyph_resolver"
    autoload :Cpal, "fontisan/tables/cpal"
    autoload :CurveConverter, "fontisan/tables/glyf/curve_converter"
    autoload :Cvar, "fontisan/tables/cvar"
    autoload :Fvar, "fontisan/tables/fvar"
    autoload :Glyf, "fontisan/tables/glyf"
    autoload :GlyfTable, "fontisan/tables/glyf_table"
    autoload :GlyphBuilder, "fontisan/tables/glyf/glyph_builder"
    autoload :Gpos, "fontisan/tables/gpos"
    autoload :Gsub, "fontisan/tables/gsub"
    autoload :Gvar, "fontisan/tables/gvar"
    autoload :Head, "fontisan/tables/head"
    autoload :HeadTable, "fontisan/tables/head_table"
    autoload :Hhea, "fontisan/tables/hhea"
    autoload :HheaTable, "fontisan/tables/hhea_table"
    autoload :Hmtx, "fontisan/tables/hmtx"
    autoload :HmtxTable, "fontisan/tables/hmtx_table"
    autoload :Hvar, "fontisan/tables/hvar"
    autoload :InstanceRecord, "fontisan/tables/fvar"
    autoload :LayoutCommon, "fontisan/tables/layout_common"
    autoload :Loca, "fontisan/tables/loca"
    autoload :LocaTable, "fontisan/tables/loca_table"
    autoload :Maxp, "fontisan/tables/maxp"
    autoload :MaxpTable, "fontisan/tables/maxp_table"
    autoload :Mvar, "fontisan/tables/mvar"
    autoload :Name, "fontisan/tables/name"
    autoload :NameRecord, "fontisan/tables/name"
    autoload :NameTable, "fontisan/tables/name_table"
    autoload :Os2, "fontisan/tables/os2"
    autoload :Os2Table, "fontisan/tables/os2_table"
    autoload :Post, "fontisan/tables/post"
    autoload :PostTable, "fontisan/tables/post_table"
    autoload :Sbix, "fontisan/tables/sbix"
    autoload :SimpleGlyph, "fontisan/tables/glyf/simple_glyph"
    autoload :Svg, "fontisan/tables/svg"
    autoload :VariationAxisRecord, "fontisan/tables/fvar"
    autoload :VariationCommon, "fontisan/tables/variation_common"
    autoload :Vvar, "fontisan/tables/vvar"
  end
end
